x1=int(input("digite el valor del vector"))
y1=int(input("digite el valor del vector"))
x2=int(input("digite el valor del vector"))
y2=int(input("digite el valor del vector"))
s=((x2-x1)**2+(y2-y1)**2)**(1/2)
print(s)